environment: stage

aws:
  region: ap-southeast-2
  deployment_role_arn: arn:aws:iam::063627630243:role/github-actions-ecs-deployment-role

network:
  # Keep sensitive/account-specific IDs in GitHub secrets.
  vpc_id_secret_name: VPC_ID
  subnet_ids_secret_name: ECS_SUBNETS
  assign_public_ip: ENABLED

ecr:
  repository: business-os-api
  image_tag_mutability: MUTABLE
  scan_on_push: true

ecs:
  cluster: business-os-cluster
  service: business-os-service
  task_family: business-os-task
  desired_count: 1
  launch_type: FARGATE
  platform_version: LATEST
  task_cpu: 512
  task_memory: 1024
  container_name: business-os-api
  container_port: 4000
  health_check_grace_period_seconds: 60

logging:
  log_group: /ecs/business-os-api
  retention_days: 14
  stream_prefix: ecs

iam:
  task_execution_role_name: ecsTaskExecutionRole
  inline_secret_policy_name: ReadBusinessOsSecrets

secrets:
  mongodb_secret_id: my-api/mongodb-uri
  mongodb_environment_name: MONGODB_URI

load_balancer:
  name: business-os-alb
  scheme: internet-facing
  listener_port: 80
  alb_security_group_name: business-os-alb-sg
  ecs_security_group_name: business-os-ecs-sg
  target_group_name: business-os-tg
  health_check_path: /health
